### ISSUE TITLE
Display a message with the number of detected workers before processing them

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#103]
### Is your feature request related to a problem? Please describe.

By default, `wws` looks for workers in the given path and any directory inside. In certain projects, you may have some extra folders like python `venv` or NodeJS modules. You don't want these folders to be processed and this will be covered by #47.

However, this issue is not easy to notice. As discussed in #101, the CLI just hangs while trying to load all the files in the given directory.

### Describe the solution you'd like

To inform the user about this, we can add a new message before start processing the workers:

```
X files are identified as workers. Start processing them
```

This message will help to spot these issues as users will notice it when waiting for `wws` to process the workers.

**Comment by gibachan** [comment]
I'd like to have this issue! 🙋
