### ISSUE TITLE
typo: python.md

### ISSUE THREAD

**Issue by Trippy3** [vmware-labs/wasm-workers-server#108]
### Describe the bug

https://github.com/vmware-labs/wasm-workers-server/blob/0b87331d9a20c8dc20309c169019a638f0376edf/docs/docs/languages/python.md?plain=1#L148-L150

In python.md, it says `To read them in Ruby,`" but shouldn't this be "`To read them in Python,` ?
It's a very small thing, but I noticed it, so I opened an issue.

### Reproduction steps

N/A

### Expected behavior

The text in python.md above will be modified.

**Comment by Angelmmiguel** [comment]
Hello @Trippy3,

Thank you for the report! AS you noticed, that's a typo error on the documentation. I will fix it 😄

**Comment by Angelmmiguel** [comment]
Done! Closed by b884f96 😄
