### ISSUE TITLE
Expose Wasm errors in stderr

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#131]
### Is your feature request related to a problem? Please describe.

When processing a request in a worker, failures may happen at two different levels:

* Recoverable errors in the worker module: the module recovers from the error. It may print relevant information to `stderr` and continue processing the request or providing an error response.
* Wasm failures: the Wasm module fails and the worker cannot recover. This may be cause by a panic in the worker, unreachable functions, or other issues. The module cannot provide a proper response and error message. `wws` returns the error (Wasm backtrace) to the handler.

In the first case, we're already printing any data sent to `stderr` from the worker. After 52076845fc079e4677b1a8dc90e93ef2916d8428, we're inheriting the `stderr` from the environment and configuring it in the WASI context. You can also configure the `stderr` when using `wws` as a library.

However, for the second case we're not printing any error and just providing a default error page:

https://github.com/vmware-labs/wasm-workers-server/blob/5631fb400c03d3239daed03b523914b87717ad83/crates/server/src/handlers/worker.rs#L72-L79

This error exposes the Wasm backtrace. This information is very relevant for debugging on both development and production.

### Describe the solution you'd like

Before sending a generic error, `wws` must print the Wasm backtrace in the terminal. The `stderr` is configurable, so the `stderr_file` (`Option<File>`) may contain a file descriptor that should be use. If it's `None`, you can directly call `eprintln!` with the proper message. 

There's a different task to improve how `wws` manages errors (#73)

### Describe alternatives you've considered

None

### Additional context

- https://github.com/vmware-labs/wasm-workers-server/pull/129#discussion_r1200220022

**Comment by carrycooldude** [comment]
Will love to work on this issue @Angelmmiguel

**Comment by carrycooldude** [comment]
Just need to ask @Angelmmiguel , I just have to add Error Msg right?

**Comment by Angelmmiguel** [comment]
> Just need to ask @Angelmmiguel , I just have to add Error Msg right?

Exactly @carrycooldude. The goal is to capture the error from the `run` method and display it in the `stderr`. However, the `stderr` is configurable, so it may be a specific file to write or the default `stderr` from the process. For that, the handler defines an `Option<File>` variable called `stderr_file`. 

If that variable is present, you should write the data to that file descriptor. If it's not present, you can just print the error using `eprintln!`.

I forgot to add that to the issue, so I also updated the description accordingly.

**Comment by Angelmmiguel** [comment]
Closed by #141 🎉
