### ISSUE TITLE
Support modules in JavaScript workers

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#149]
### Is your feature request related to a problem? Please describe.

At a first approach, the JavaScript workers follow the Web Workers API. It requires to subscribe to a specific event and then, process the request and provide a response:

https://github.com/vmware-labs/wasm-workers-server/blob/51da71082e4cd41d787b88354d1e14c69ce22f43/examples/js-params/fixed.js#L27-L30

However, the current JavaScript SDK emulates this behavior, so it doesn't provide any Web API behind it. In addition to that, other platforms like Cloudflare and Vercel started to simplify this syntax in favor of ECMA modules:

```javascript
export default {
  async fetch(request) {
    const body = `Hello world!`;
    return new Response(body);
  },
};
```

This syntax is simpler and more convenient.

### Describe the solution you'd like

I want to write workers using the ECMA modules approach, while keeping compatibility with existing modules based on the Web Workers API.

It requires to change the current JavaScript SDK to:

* [ ] Manage ECMA modules
* [ ] Detect the current approach
* [ ] Run the worker to get the response

**Comment by mtt-artis** [comment]
Why export an object and not the fetch function directly?
Is it a standard that emerges from other platforms?

**Comment by Angelmmiguel** [comment]
> Why export an object and not the fetch function directly? Is it a standard that emerges from other platforms?

Yes! One of the goals of `wws` is to keep compatibility with other platforms. For example, you can take a worker from `wws` and run it in Cloudflare or Fastly. We're following the [WinterCG](https://wintercg.org/) standard and taking Cloudflare as a reference for the syntax on the JavaScript workers: https://developers.cloudflare.com/workers/examples/return-html/.

**Comment by Angelmmiguel** [comment]
I'm really happy to close this task! 👏
