### ISSUE TITLE
There are some problems building the image

### ISSUE THREAD

**Issue by dierbei** [vmware-labs/wasm-workers-server#183]
### Describe the bug

I try to use the command `buildx build -t wws:0938 -f image/Dockerfile` , but I have a problem: 

![image](https://github.com/vmware-labs/wasm-workers-server/assets/52097565/47ab7d78-8a7e-4ecf-96e8-ece8e4ec0cd0)

So I tried to modify the image to `rust:1.66.0-slim` and tried to build again. But again I got an error, seems to be missing `openssl`：

![image](https://github.com/vmware-labs/wasm-workers-server/assets/52097565/3a9b4277-6a2a-4028-9ff9-99a5d5b66595)

So I tried to modify the image again and changed it to `rust:1.66.0`, To my surprise, the build was successful.

### Reproduction steps

I tried to run it using the built image, but I encountered a problem and I don't know how to solve it.

![image](https://github.com/vmware-labs/wasm-workers-server/assets/52097565/a963136d-c60c-4c35-9d2a-f43f83e45467)

### Expected behavior

run successfully

**Comment by ereslibre** [comment]
Thank you for this report @dierbei! I have opened https://github.com/vmware-labs/wasm-workers-server/pull/184 to address all the issues.

**Comment by ereslibre** [comment]
@dierbei Everything should be fine now, please reopen if any of the mentioned issues persist.
