### ISSUE TITLE
Add support for Wasm components

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#227]
### Is your feature request related to a problem? Please describe.

Wasm components ([component-model proposal](https://component-model.bytecodealliance.org/)) are close to hit a milestone. The WASI preview2 release is close and it's based on components. Several projects like [Runwasi](https://github.com/containerd/runwasi/) started to [integrate components as the main entrypoint for applications](https://docs.google.com/document/d/11shgC3l6gplBjWF1VJCWvN_9do51otscAm0hBDGSSAc/edit).

I would like to continue using Wasm Workers Server to run this kind of modules.

### Describe the solution you'd like

Wasm Workers Server will continue supporting multiple application types. From source code files to core modules and components. `wws` will detect the different types automatically and route requests to them. For now, we will only support Rust, but we expect to start supporting more languages via `wit-bindgen`. 

Existing workers will continue working. `wws` will configure the runtime and prepare the context for every worker.

**Comment by ereslibre** [comment]
Implemented in https://github.com/vmware-labs/wasm-workers-server/pull/225
