### ISSUE TITLE
Configure maximum logging level

### ISSUE THREAD

**Issue by assambar** [vmware-labs/wasm-workers-server#253]
### Is your feature request related to a problem? Please describe.

Sometimes (e.g. when deploying) we may not want to have detailed logging at the console.

### Describe the solution you'd like

Add an option `--log-level,l={trace|debug|info|warn|error|off}`, passed on start of `wws`, which will determine the minimum logging level for the application.

Default would be `info`.

If there is a set `RUST_LOG` env variable and `--log-level` is not specified - do not set anything, just let `RUST_LOG` be.

**Comment by Angelmmiguel** [comment]
Related to https://github.com/vmware-labs/wasm-workers-server/discussions/252
