### ISSUE TITLE
Add an option to ignore certain folders

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#47]
When running `wws`, it will fetch all the files in the given directory and subfolders. Sometimes, we may run the CLI in a folder, but we don't want to check all the folders inside it. For example, we want `wws` to be able to ignore `node_modules` folders in certain cases.

To make it configurable, we plan to add a new option to the CLI called `--ignore`. This `--ignore` option can be used multiple times to ignore several folders:

```
wws --ignore node_modules --ignore tmp .
```

Clap supports already supports this feature. The complexity of this issue comes from:

* The support of Windows and Unix systems
* Usage of `Glob` crate

Note that if we use the same approach we do for skipping the `public` folder, `Glob` will still list all the files in those folders. Folders lik `node_modules` can cause a performance issue as they may contain a big number of supported files (`.js`).

**Comment by assambar** [comment]
Could we use a .wwsignore file instead? Placed anywhere in a scanned folder tree (just like .gitignore)
It is more complex, but for different languages or frameworks that one uses to create their workers we might end up with bunches of different folder names that we want to ignore.
And if we have to provide all of them on the commandline it could become hard to maintain.

**Comment by Angelmmiguel** [comment]
That's a good option. I would even rely in `.gitgnore` if it's present. However, I still think the option is useful as it can be a direct command: `wws --ignore X .`. 

I also like the idea to take into account your `.gitignore` file. This allows to reuse an existing configuration so you don't need to create an extra file if it's created. Although, this may be confusing.

So, +1 on supporting the `.wwsignore` file + `--ignore` option.
