### ISSUE TITLE
Add support for Golang

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware-labs/wasm-workers-server#95]
[Golang](https://go.dev/) is a popular programming language. Currently, you can compile Go apps to Wasm + WASI using [TinyGo](https://tinygo.org/docs/guides/webassembly/). The Go team will release a formal support for Wasm + WASI (preview1) in 1.21 (August 2023).

Golang can be compiled to WebAssembly, so there's no requirement of a language runtime like Python, Ruby or JavaScript. The goal for this task is to create the wrapper code to interact with Wasm Workers Server. The same approach we took for the [Rust support](https://github.com/vmware-labs/wasm-workers-server/tree/main/kits/rust).

## Technical requirements

These are the for the Golang support:

1. Read the JSON metadata that comes via STDIN. Here you have the example from the Rust kit:

    https://github.com/vmware-labs/wasm-workers-server/blob/5631fb400c03d3239daed03b523914b87717ad83/kits/rust/src/io.rs#L15-L23

1. Define the `Request`, `Response` and `Cache` entities. If it's available, it's better to use primitives from the Golang standard library or common usage libraries. 
1. Initialize a `Request` object from the JSON metadata.
1. Initialize the Cache store.
1. Call the worker function with the `Request` instance.
1. Detect the content in the response. If it's a valid UTF-8 string, we can return. If it uses a different encoding, you need to encode it in base64.
1. Transform the response and the Cache status into the expected JSON output. Note that the `base64` flag is only enabled when the content is encoded. 

    https://github.com/vmware-labs/wasm-workers-server/blob/5631fb400c03d3239daed03b523914b87717ad83/kits/rust/src/io.rs#L59-L65

1. Print the JSON output via STDOUT

## Additional notes

* The library should be defined in the `kits/go` folder.
* The documentation is available in the site: https://workers.wasmlabs.dev/docs/languages/introduction.
* Currently, we're not publishing the libraries to language registries. Instead, we document how to get it from the GitHub repository.

**Comment by Angelmmiguel** [comment]
That's amazing @mnafees! I assigned the task to you to keep track of it. I also updated the task to provide a better description of the requirements to complete it.

Please, feel free to ask any question and open a draft PR in case you want to share some early code for feedback 😄

**Comment by mnafees** [comment]
Hi @Angelmmiguel, opened a basic draft PR. I will be updating the PR with examples in a following commit!

**Comment by Angelmmiguel** [comment]
> Hi @Angelmmiguel, opened a basic draft PR. I will be updating the PR with examples in a following commit!

That's amazing! I already enabled the CI on the PR.
